project:
  type: website
  output-dir: docs

website:
  title: "Emrys King"
  favicon: logo.png
  navbar:
    logo: logo.png
    logo-alt: "A hypercube logo."
    search: true
    right:
      - href: index.qmd
        text: " "
      - projects.qmd
      - cv.qmd
  search:
    location: navbar
    type: textbox
  page-footer:
    left:
      - text: "&copy; Copyright 2026, Emrys King. All rights reserved."
    right:
      - icon: github
        href: https://github.com/egkegk/egkegk.github.io
        aria-label: "Quarto GitHub"
    background: "#f7f4ea"

format:
  html:
    theme:
      - flatly
      - theme.scss
    mainfont: Radley
    toc: true

editor: source

